[logconfig_file]
name=/home/hemanta/pkcs11-client/EC_PKCS11_CLIENT-LogConfig.xml

[server_url]
;url=https://lunacodesignsecure.encryptionconsulting.com
url=https://devcodesignsecure.encryptionconsulting.com
;url=http://127.0.0.1:6666

[pfxfile_path]
path=/home/hemanta/pkcs11-client/AuthCert-nCipher.pfx

[pfxfile_passwd]
passwd=8bfd8f24f055
